project: 
  type: website
  
website:
  page-navigation: true
  image:  images/banner.jpeg
  site-url: "https://colorado.posit.co/rsc/example-community-site/" 
  repo-url: "https://github.com/RachaelDempsey/example-company-community-site" 
  repo-actions: [source]
  navbar: 
    search: true
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Upcoming Events"
        file: upcoming-events.qmd
      - text: "Recordings"
        file: resources.qmd
      - text: "Data Science Tools"
        file: tools.qmd
  
  page-footer:
    right: "This page is built with 🖤 and [Quarto](https://quarto.org/)."
    
format:
  html:
    layout:
    title-block-categories: false
    title-block-banner: images/banner-1068.png
    theme: minty
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua
  - quarto
